Login and Register
JoakoCassina/Grupo_5_JACA-TECH pull request #7
Opened 2023-10-09 16:22 UTC by Kokun35

ahi cree los formularios de Login y el de Registro!! Veanlo avisenme que les parece!!!
El formulario de registro la idea es que en desktop se vea a lo anho dividio en 2 pero como todavia no vimos lo que seria displey: grid lo deje asi.

2023-10-09 19:03 UTC, aleseravalle requested changes

2023-10-09 19:03 UTC, aleseravalle commented on src/views/register.html
> +                        <label><input type="checkbox">He leido y acpeto los</label>
He leido y acpeto los terminos y condiciones de Usuario - cambiar acepto

2023-10-10 00:03 UTC, Kokun35 commented on src/views/register.html
> +                        <label><input type="checkbox">He leido y acpeto los</label>
correccion de error y agregado del button de reset

2023-10-10 00:10 UTC, aleseravalle approved these changes
todo bien!!

2023-10-10 00:27 UTC, agubeninca commented
Todo ok!

2023-10-10 00:31 UTC, merged